#!/bin/bash


#fix audio driver for thinkpad
#sudo vim /etc/modprobe.d/inteldsp.conf
#options snd_intel_dspcfg dsp_driver=1

#sudo apt install gcc xorg git xserver-xorg make vim screen progress python3 python3-pip alsa-utils pavucontrol pcmanfm suckless-tools lightdm terminator wget curl network-manager network-manager-gnome xinput brightnessctl vlc ffmpeg i3lock xss-lock unzip zsh neofetch tmux
#fix tuchpad tap
#xinput list
#xinput list-props [device number]
#xinput set-prop [device number] [option number] 1
#
#
#brave install
#sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
#echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list
#sudo apt install brave-browser

#install protonvpn
#https://repo.protonvpn.com/debian/dists/stable/main/binary-all/protonvpn-stable-release_1.0.3-2_all.deb# sudo dpkg -i protonvpn-stable-release_1.0.3-2_all.deb
#sudo apt-get install protonvpn-cli
# needs network-manager applet needs to be running nm-applet &
#setup NetworkManager
#sudo vim /etc/network/interfaces
#comment out interfaces

# Installing qtile on debian 12 bookworm
# move and back-up the EXTERNALLY-MANAGED file so pip works
# sudo mv /usr/lib/python3.11/EXTERNALLY-MANAGED /usr/lib/python3.11/EXTERNALLY_MANAGED.bak

# Install the full Python 3 Suite, pip, git and all Dependencies
# sudo apt update
# sudo apt install python3-full python3-pip libpangocairo-1.0-0 python3-cffi python3-xcffib -y

# Install cairocffi using pip
# pip install --no-cache-dir cairocffi

# Clone the Qtile Source Code from GitHub and Install
# git clone https://github.com/qtile/qtile.git
# cd qtile
# pip install .

# Xsessions Desktop file
# sudo vim  /usr/share/xsessions/qtile.desktop
# add below to file
#[Desktop Entry]
#Name=Qtile
#Comment=Qtile Session
#Type=Application
#Keywords=wm;tiling
#Exec=/home/username/.local/bin/qtile start


sudo echo "Exec=/home/$USER/.local/bin/qtile start" | sudo tee -a /usr/share/xsessions/qtile.desktop

